weibocom/opendcp

- build.sh
- deploy/docker-compose.yml
add check for result of building image.
> add check for result of building image.

- imagebuild/code/project/plugged_project.go
- ui/api/for_repos/package.php
- ui/for_repos/package.php
- ui/js/for_repos/package.js
> 【imageBuild】任务

- ui/api/for_repos/tags.php
- ui/for_repos/repos.php
- ui/js/for_repos/repos.js
1、增加操作按钮
2、显示镜像的完整信息（推送的Harbor仓库地址以及镜像名称）比如：10.85.41.167:12380/myweb4:6.7
> 【imageBuild】任务2

- db_init/sql/web.sql
> 修改多租户支持初始化SQL

- jupiter/controllers/cluster.go
- jupiter/controllers/instance.go
- jupiter/controllers/slb.go
- jupiter/dao/cluster.go
- jupiter/dao/instance.go
- jupiter/future/ansible.go
- jupiter/future/start.go
- jupiter/models/cluster.go
- jupiter/models/instance.go
- jupiter/service/bill/bill.go
- jupiter/service/cluster/cluster.go
- jupiter/service/instance/instance.go
Filter info based on bizId when invoke interface about instance and cluster!
> Filter info based on bizId.

- orion/handler/remote_handler.go
- orion/service/remote.go
> 服务编排支持多租户（过滤）

- db_init/sql/imagebuild.sql
- imagebuild/code/handler/abstract_extensible_handler.go
- imagebuild/code/handler/extensible_docker_file_generator.go
- imagebuild/code/handler/handler_info.go
- imagebuild/code/model/build_history.go
- imagebuild/code/plugin/plugin_pipeline.go
- imagebuild/code/plugin/plugin_wrapper.go
- imagebuild/code/plugins/dockerfile/download_dockerfile/download_dockerfile_plugin.go
- imagebuild/code/plugins/dockerfile/download_executable_source/download_executable_source_plugin.go
- imagebuild/code/project/plugged_project.go
- imagebuild/code/project/project.go
- imagebuild/code/server.go
- imagebuild/code/service/build_history_service.go
- imagebuild/code/util/file_util.go
- imagebuild/code/web/controllers/basic_controller.go
- imagebuild/code/web/controllers/build_histories_controller.go
- imagebuild/code/web/controllers/build_image_controller.go
- imagebuild/code/web/controllers/build_image_history_controller.go
- imagebuild/code/web/controllers/config_save_controller.go
- imagebuild/code/web/controllers/config_view_controller.go
- imagebuild/code/web/controllers/independent_config_view_controller.go
- imagebuild/code/web/controllers/info_view_controller.go
- imagebuild/code/web/controllers/project_clone_controller.go
- imagebuild/code/web/controllers/project_delete_controller.go
- imagebuild/code/web/controllers/project_info_controller.go
- imagebuild/code/web/controllers/project_list_controller.go
- imagebuild/code/web/controllers/project_new_controller.go
- imagebuild/globle_config/plugins.html
- imagebuild/sql/init.sql
1、后端数据库新增字段cluster。
2、【镜像市场-镜像仓库】新增初始化接口，和修改项目查询接口。
3、【镜像市场-打包系统】重新定义文件组织结构，保证支持多租户
> 【镜像市场】多租户支持

- imagebuild/code/project/project.go
- imagebuild/code/server.go
> 【Bug-镜像市场】修复新建项目出错

- db_init/sql/jupiter.sql
- jupiter/dao/cluster.go
- jupiter/dao/instance.go
- jupiter/routers/commentsRouter_controllers.go
- jupiter/service/cluster/cluster.go
Fix the instance list bug and db init bug!
> Fix multi tenancy bugs.

- jupiter/routers/commentsRouter_controllers.go
> Fix initdb err!

- jupiter/controllers/cluster.go
- jupiter/controllers/init.go
- jupiter/controllers/instance.go
- jupiter/routers/commentsRouter_controllers.go
- jupiter/service/instance/instance.go
- Fix the credit check bug.
- Fix initdb bug in jupiter.
> Fix some bugs

- ui/js/for_cloud/account.js
- ui/js/navicate.js
> Dev bppan imagebuild

- db_init/sql/orion.sql
- orion/api/exec.go
- orion/api/flow.go
- orion/executor/flow_executor.go
- orion/helper/common_flows.go
- orion/models/task.go
- orion/service/flow.go
- ui/js/for_layout/taskdetail.js
1、任务支持失败、完成重运行
2、节点从错误步骤开始执行
3、数据库表node_state增加字段step_num
> 【服务编排】任务管理

- orion/api/flow.go
- orion/executor/flow_executor.go
- ui/opendcp_data.php
> 【服务编排】任务支持，暂停，继续

- .gitignore
- orion/executor/flow_executor.go
- orion/main.go
- orion/models/task.go
- orion/sched/internal/cron/cron.go
- orion/sched/internal/cron/cron_job.go
- orion/sched/internal/cron/cron_test.go
- orion/sched/internal/scaler/depend.go
- orion/sched/internal/scaler/logger.go
- orion/sched/internal/scaler/node.go
- orion/sched/internal/scaler/scaler.go
- orion/sched/scheduler.go
- orion/sched/scheduler_test.go
This functionality makes the expand/shrink tasks auto-run by given
time and instance number.
> add crontable task implement

- orion/sched/internal/scaler/scaler.go
- orion/sched/scheduler.go
fixed: the crontable task is stopped after Create/Update
> fixed: the crontable task is stopped after Create/Update

- orion/sched/internal/cron/cron.go
- orion/sched/internal/scaler/scaler.go
fixed: choose wrong cronitem of crontable task in add task step
> fixed: choose wrong cronitem of crontable task in add task step

- ui/api/for_hubble/nginx_node.php
> nginx节点增加删除接口

- ui/js/opendcpData.js
> fix dashboard of openDCP

- deploy/docker-compose.yml
restart docker container the data can't not be lost
> imagebuild add volum

- jupiter/future/start.go
- jupiter/service/instance/instance.go
> 修改 start.go 冲突

- deploy/docker-compose.yml
> add depends orion

- hubble/Application/V1/Controller/Nginx/TimingController.class.php
> change timing

- hubble/Application/Common/Dao/Adaptor/Adaptor.class.php
> change return to timing

- hubble/Application/Common/Dao/Adaptor/Channel.class.php
> add Service discovery id

- hubble/Application/Common/Dao/Adaptor/AlterationHistory.class.php
add the method of addTaskRecord
> add the method of addTaskRecord

- hubble/Application/Common/Dao/Common/LogDb.class.php
> change gid

- db_init/sql/hubble.sql
> change alteration_history

- hubble/Application/V1/Controller/Nginx/TimingController.class.php
change the method about timing
> change the method about timing

- hubble/Application/Common/Dao/Nginx/Upstream.class.php
change the method of _fileAddNode
> change the method of _fileAddNode

- README.md
> update video url

- README.md
> modify video url
